### PR TITLE
Modification on Visualisation

### PR DESCRIPTION
**Pull request by ranimeelzein**
fix time X axis and commented print to stdout

### CODE REVIEW

**Comment by lebenebou** [comment]
When the dataset is large, the time intervals on the X axis become mushed together. Maybe consider keeping the same data but only plotting SOME of the intervals on the X axis.

thanks ranim love you

**Comment by ranimeelzein** [comment]
to import the library:
pip install plotly 
pip install dash

**Comment by lebenebou** [comment]
I think this is a better library! And thanks for providing pip install commands.

Still no pie chart?? :(

thanks ranim love you

**Comment by lebenebou** [comment]
image

For the battery, can you please anchor the Y axis to always be between 0 and 100?
For example, here it is between 95 and 100 which is not what the user should see.

love you thanks Ranim

**Pull request merged**
